[package]
name = "slice_type"
version = "0.1.0"
authors = ["sam-g99 <46730010+sam-g99@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
